In [19]:
import numpy as np
from numpy.linalg import inv, solve

In [2]:
c = np.array([1,2,3])
r = np.array([[1,2,3]])
print(c.shape, r.shape)

(3,) (1, 3)


In [3]:
# np.zeros((2,2))
# np.ones((2,2))
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [4]:
d = np.random.random((2,2)) # uniform random
print(d)

[[0.18310811 0.74486381]
 [0.13326392 0.78280288]]


In [6]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[1,2,3,4],[5,6,7,8]])
A.dot(B)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [13]:
A = np.array([[1,2,3],[5,4,3],[7,9,8]])
A_inv = inv(A)
A_inv

array([[ 0.27777778,  0.61111111, -0.33333333],
       [-1.05555556, -0.72222222,  0.66666667],
       [ 0.94444444,  0.27777778, -0.33333333]])

In [15]:
A * A_inv # element-wise multiplication

array([[ 0.27777778,  1.22222222, -1.        ],
       [-5.27777778, -2.88888889,  2.        ],
       [ 6.61111111,  2.5       , -2.66666667]])

In [18]:
A.dot(A_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16,  1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [23]:
# AX = b
b = np.random.random((3,1))
X = A_inv.dot(b)
X

array([[ 0.07431561],
       [-0.28433372],
       [ 0.31643724]])

In [24]:
X = solve(A, b)
X

array([[ 0.07431561],
       [-0.28433372],
       [ 0.31643724]])