# Random Forest

## p. 95-103 Random Forest 이론
ppt와 필기 참고

## p.104~) Iris 데이터를 이용해 간단한 Random Forest 구현

In [5]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [9]:
#loading the iris dataset
iris = load_iris()
len(iris["data"])

150

In [30]:
#training data 설정 : 전체 iris data에서 처음부터 마지막 30번째 데이터 까지를 training data로 설정
x_train = iris.data[:-30]
y_train = iris.target[:-30]

#test data 설정 : 마지막 30번쩨 데이터부터 끝까지를 test data로 설정
x_test = iris.data[-30 : ]
y_test = iris.target[-30 : ]

- Training data의 target 출력

In [31]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]


- Test data의 target 출력

In [32]:
print(y_test) #전부 2, training data와 test data 잘못 분리

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


### Random Forest 분류기 생성
- Random Forest 분류기 생성을 위해 RandomForestClassifier 클래스를 import
- sklearn.ensemble 모듈은 분류, 회귀 및 이상 탐지를 위한 ensemble-based 방법을 포함

In [33]:
#RandomForestClassifier 클래스를 import
from sklearn.ensemble import RandomForestClassifier

In [113]:
#tree의 개수 RandomForest 분류 모듈 생성
rfc = RandomForestClassifier(n_estimators = 10) #n_estimators : 트리 개수 지정
rfc

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [114]:
#training set으로 모델 생성
rfc.fit(x_train, y_train)

#Test data를 입력해 target data를 예측
prediction = rfc.predict(x_test)

#예측 결과 prediction과 실제 test data의 target을 비교
print(prediction == y_test)

[ True False  True False  True  True False False  True False  True  True
  True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True]


In [115]:
#뇌피셜 데이터로 예측해보기
mydata = np.array([
                    [4.9, 3.4, 1.5, 2.3],
                    [4.6, 3.0, 1.4, 1.8]])
mypredict = rfc.predict(mydata)
mypredict

array([0, 0])

- Random Forest 분류기 성능 평가(1)

In [116]:
#Random Forest 정확도 측정
rfc.score(x_test, y_test)

0.8

- Random Forest 분류기 성능 평가(2)

In [117]:
prediction

array([2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [118]:
#np.array의 빈도수 보기
#예측한 y값
import collections
collections.Counter(prediction)

Counter({2: 24, 1: 6})

In [119]:
#실제 y_test값
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [120]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediction, labels=[0, 1, 2])

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  6, 24]], dtype=int64)

In [121]:
confusion_matrix(y_test, prediction) #필기에 맞는 confusion matrix

array([[ 0,  0],
       [ 6, 24]], dtype=int64)

In [111]:
?accuracy_score

In [110]:
?classification_reportaccuracy_score(y_test, prediction)

In [124]:
from sklearn.metrics import accuracy_score, precision_score
from sklearn.metrics import classification_report

print("Accuracy is : ", accuracy_score(y_test, prediction))
print("="*100)

#classification_report : 각각의 값에 대해 성능 평가 값을 제공(필기 참고)
#macro avg : 1과 2의 성능 평가 값들의 평균, weight avg : 많이 예측한 결과에 가중치를 더 실어 평균을 냄
print(classification_report(y_test, prediction)) 

Accuracy is :  0.8
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       1.00      0.80      0.89        30

    accuracy                           0.80        30
   macro avg       0.50      0.40      0.44        30
weighted avg       1.00      0.80      0.89        30



In [123]:
print(classification_report(prediction, y_test)) 

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         6
           2       0.80      1.00      0.89        24

    accuracy                           0.80        30
   macro avg       0.40      0.50      0.44        30
weighted avg       0.64      0.80      0.71        30



C:\education\bigdata\python\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
#decision tree는 특징추출시에 많이 사용(전처리)

- 파이썬에 빙의해 precision과 recall을 계산

In [75]:
arr = np.array([[23, 7],[0,0]])
arr

array([[23,  7],
       [ 0,  0]])

In [73]:
precision = 23/23
precision

1.0

In [74]:
recall = 23/30
recall

0.7666666666666667

P.113-116까지 실습

- Training, Test 데이터 재 생성

In [139]:
from sklearn.model_selection import train_test_split
x = iris.data
y = iris.target
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, stratify = y)#각각 범주의 비율을 같게 하고싶다면 stratify = y추가
print(y_test) #맘대로 뽑은 이전 데이터
print(Y_test) # random하게 뽑은 데이터

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[1 0 2 0 0 1 0 2 2 1 0 2 0 0 0 1 2 1 1 1 0 2 1 2 1 2 0 2 1 2]


In [145]:
clf = RandomForestClassifier(n_estimators=10)
clf.fit(X_train, Y_train)
prediction = clf.predict(X_test)

print("Accuracy is : ", accuracy_score(Y_test, prediction))
print("="*100)

#classification_report : 각각의 값에 대해 성능 평가 값을 제공(필기 참고)
#macro avg : 1과 2의 성능 평가 값들의 평균, weight avg : 많이 예측한 결과에 가중치를 더 실어 평균을 냄
print(classification_report(Y_test, prediction)) 

Accuracy is :  0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



#### Random Forest 분류기 성능 높이기
- tree의 개수(n_estimators)를 변경
- max_features의 값을 변경(모델 생성에 사용될 column의 개수를 지정)

In [146]:
clf_2 = RandomForestClassifier(n_estimators=200,
                            max_features=4,
                            oob_score=True)
clf_2.fit(X_train, Y_train)
#prediction = clf_2.predict(X_test)

#print("Accuracy is : ", accuracy_score(Y_test, prediction))
#print("="*100)

#classification_report : 각각의 값에 대해 성능 평가 값을 제공(필기 참고)
#macro avg : 1과 2의 성능 평가 값들의 평균, weight avg : 많이 예측한 결과에 가중치를 더 실어 평균을 냄
print(classification_report(Y_test, prediction)) 

Accuracy is :  0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [142]:
clf_2 = RandomForestClassifier(n_estimators=200,
                            max_features=4,
                            oob_score=True)
clf_2.fit(X_train, Y_train)
print("oob score : ", clf_2.oob_score_)
#prediction = clf_2.predict(X_test)

#print("Accuracy is : ", accuracy_score(y_test, prediction))
#print("="*100)

#classification_report : 각각의 값에 대해 성능 평가 값을 제공(필기 참고)
#macro avg : 1과 2의 성능 평가 값들의 평균, weight avg : 많이 예측한 결과에 가중치를 더 실어 평균을 냄
#print(classification_report(y_test, prediction)) 

oob score :  0.95


- 각 featuer의 중요도 확인

In [148]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [149]:
clf_2.feature_importances_ #oob_score를 만드는데 해당 변수가 얼마나 영향을 미쳤는가? 

array([0.01595274, 0.01330831, 0.45443112, 0.51630783])

In [147]:
for feature, imp in zip(iris.feature_names, clf_2.feature_importances_):
    print(feature, imp)

sepal length (cm) 0.015952735837625267
sepal width (cm) 0.013308310471720302
petal length (cm) 0.45443112343748504
petal width (cm) 0.5163078302531694
